# Generated by Django 3.2.5 on 2023-01-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='File_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.ForeignKey(db_column='filename', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='main.board')),
            ],
        ),
    ]
