# Generated by Django 3.2.5 on 2023-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='data',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='data',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
